const products = [
    {
        id: 1,
        image:"./book images/38.jpg",
        name: "Stephen Hawking",
        price: 333,
    },
    {
        id: 2,
        image:"./book images/3.jpg",
        name: "Dictionary Оxford",
        price: 499, 
    },
    {
        id: 3,
        image:"./book images/7.jpg",
        name: "James Joyce",
        price: 799,
    },
    {
        id: 4,
        image:"./book images/29.jpg",
        name: "Victor Pelevin",
        price: 388,
    },
    {
        id: 5,
        image:"./book images/31.jpg",
        name: "Fairy tales",
        price: 380,
    },
    {
        id: 6,
        image:"./book images/19.jpg",
        name: "Clifford Simak",
        price: 310,
    },
    {
        id: 7,
        image:"./book images/28.jpg",
        name: "Sergei Minaev",
        price: 350,
    },
    {
        id: 8,
        image:"./book images/35.jpg",
        name: "Napoleon Hill",
        price: 670,
    },
    {
        id: 9,
        image:"./book images/24.jpg",
        name: "Stephen King",
        price: 222, 
    },
    {
        id: 10,
        image:"./book images/20.jpg",
        name: "Clifford Simak",
        price: 300,
    },
    {
        id: 11,
        image:"./book images/6.jpg",
        name: "John Updike",
        price: 333,
    },
    {
        id: 12,
        image:"./book images/34.jpg",
        name: "Elena Blavatsky",
        price: 799,
    },
    {
        id: 13,
        image:"./book images/30.jpg",
        name: "George Orwell",
        price: 300,
    },
    {
        id: 14,
        image:"./book images/15.jpg",
        name: "Stephen King",
        price: 110,
    },
    {
        id: 15,
        image:"./book images/21.jpg",
        name: "Clifford Simak",
        price: 177,
    },
    {
        id: 16,
        image:"./book images/32.jpg",
        name: "Thomas Ricks",
        price: 670,
    },
    {
        id: 17,
        image:"./book images/26.jpg",
        name: "Mikhail Hrushevsky",
        price: 399,
    },
    {
        id: 18,
        image:"./book images/16.jpg",
        name: "Muller Dictionary",
        price: 460,
    },
    {
        id: 19,
        image:"./book images/14.jpg",
        name: "Ukrainian Dictionary",
        price: 170,
    },
    {
        id: 20,
        image:"./book images/5.jpg",
        name: "Ukrainian laws",
        price: 890,
    }
];
